# Cloudflare Pages Configuration
# Wrangler configuration for OpenNext + Cloudflare deployment

name = "digidocs"
compatibility_date = "2024-09-01"

# Tell Cloudflare where OpenNext outputs the build for Cloudflare platform
pages_build_output_dir = ".open-next"

# Node.js compatibility for Next.js server functions
compatibility_flags = ["nodejs_compat"]

# Environment variables (only non-secret values here)
# Secrets must be set in Cloudflare Dashboard → Settings → Environment Variables
