# Cloudflare Pages Configuration
# This file is optional for Pages deployment but useful for advanced configurations

name = "digidocs"
compatibility_date = "2024-01-01"

# Pages-specific configuration
pages_build_output_dir = ".vercel/output/static"

# Environment variables can be set in Cloudflare Dashboard
# This file should NOT contain secrets

[build]
command = "pnpm run build"
cwd = ""

[build.upload]
format = "service-worker"

# Node.js compatibility for API routes
compatibility_flags = ["nodejs_compat"]

