# Cloudflare Pages Configuration
# Wrangler configuration for OpenNext + Cloudflare deployment

name = "digidocs"
compatibility_date = "2024-09-01"

# Tell Cloudflare where @cloudflare/next-on-pages outputs the build
pages_build_output_dir = ".vercel/output/static"

# Node.js compatibility for Next.js server functions
compatibility_flags = ["nodejs_compat"]

# Environment variables (only non-secret values here)
# Secrets must be set in Cloudflare Dashboard → Settings → Environment Variables
